config/routes.rb
Rails.application.routes.draw do
  # Routes - Devise (automatically created)
  devise_for :users  
  #   new_user_session GET         /users/sign_in(.:format)        devise/sessions#new
  #   user_session POST            /users/sign_in(.:format)        devise/sessions#create
  # destroy_user_session DELETE    /users/sign_out(.:format)        devise/sessions#destroy
  # new_user_password GET          /users/password/new(.:format)     devise/passwords#new
  # edit_user_password GET         /users/password/edit(.:format)   devise/passwords#edit
  #  user_password PATCH           /users/password(.:format)        devise/passwords#update
  #                PUT             /users/password(.:format)        devise/passwords#update
  #                POST            /users/password(.:format)        devise/passwords#create
  # cancel_user_registration GET   /users/cancel(.:format)         devise/registrations#cancel
  # new_user_registration GET      /users/sign_up(.:format)        devise/registrations#new
  # edit_user_registration GET     /users/edit(.:format)           devise/registrations#edit
  # user_registration PATCH        /users(.:format)                devise/registrations#update
  #                PUT             /users(.:format)                devise/registrations#update
  #                DELETE          /users(.:format)                devise/registrations#destroy
  #                POST            /users(.:format)                devise/registrations#create
  
  # Routes - Listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"

  get "/listings/:id/purchase", to: "listings#purchase", as: "purchase_listing"
  
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  delete "/listings/:id", to: "listings#destroy"
  
  # Routes - Landing Page
  get "/", to: "pages#home", as: "root"

  # Routes - Question (Only need create route, as get/form will be shown on show_listing)
  post "/listings/:id/questions", to: "questions#create", as: "questions"

  # Routes - Answer (Only need create route, as get/form will be shown on show_listing)
  post "/questions/:id/answers", to: "answers#create", as: "answers"

  # Routes - Profile (:id here is the id column in User table)
  get "/profiles/:id", to: "profiles#show", as: "profile"

  # Routes - Advanced Searches
  post "/searches", to: "searches#create", as: "searches"
  get "/searches/new", to: "searches#new", as: "new_search"
  get "/searches/:id", to: "searches#show", as: "search"

  # Routes - Payment
  get "/payments/success", to: "payments#success", as: "success_payment"
  post "/payments/webhook", to: "payments#webhook", as: "webhook_payment"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :location
  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true
  has_many :questions, dependent: :destroy
  has_one_attached :pic
  enum category: { face: 0, eyes: 1, lips: 2, accessories: 3 } 
  validates :title, :brand, :price, :category, :description, :user_id, :pic, presence: true
  has_one :purchase, dependent: :destroy
  
  def self.search(search)
    if search
      where(["lower(title) LIKE ?", "%#{search.downcase}%"])
    else
      all
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:show, :edit, :update, :destroy, :purchase]
    before_action :set_user_listing, only: [:edit, :update, :destroy]
    # Only users own the listings can perform these actions
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :purchase]
    # Users need to log in to perform these actions

    def index
      # Simple search
      if :search
        @listings = Listing.search(params[:search])
      else
        # Only show available listings
        @purchase = Purchase.pluck(:listing_id)
        @listings = Listing.where.not(id: @purchase)
      end
    end

    def new
      # Nested attributes for location
      @listing = current_user.listings.new
      @listing.build_location
    end

    def create
        @listing = current_user.listings.create(listing_params) 
      if @listing.errors.any?
          render "new"
      else 
          redirect_to listing_path(@listing)
      end
    end

    def show
      # Simple search
      @listings = Listing.search(params[:search])

      @suburb = @listing.location[:suburb]
      @postcode = @listing.location[:postcode]
      @state = @listing.location[:state]
      
      # Q & A
      @question = Question.new
      @answer = Answer.new
    end

    def purchase
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @listing.title,
            amount: @listing.price * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                listing_id: @listing.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
        cancel_url: "#{root_url}listings"
      )
      @session_id = session.id
      @public_key = Rails.application.credentials.dig(:stripe, :public_key) 
    end

    def edit
    end

    def update
          if @listing.update(listing_params)
            redirect_to listing_path(@listing)  
          else
            render "edit"
        end
    end
    
    def destroy
        @listing.destroy
        redirect_to(listings_path)
    end

    private
 
    def listing_params
      params.require(:listing).permit(:title, :brand, :price, :description, :category, :user_id, :pic, :search, location_attributes: [:suburb, :postcode, :state, :_destroy])
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_user_listing
        @listing = current_user.listings.find_by_id(params[:id])

        if @listing == nil
            redirect_to listings_path
        end
    end
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category, [["Face", "face"], ["Eyes", "eyes"], ["Lips", "lips"], ["Accessories", "accessories"]]) %>
  </div>

  <div class="field">
    <%= form.label :price, "Price $" %>
    <%= form.number_field :price, min: 0 %>
  </div>


  <%= form.fields_for :location do |l| %>
    <div class="field"> 
      <%= l.label :suburb %>
      <%= l.text_field :suburb %>
    </div>

    <div class="field"> 
      <%= l.label :postcode %>
      <%= l.text_field :postcode %>
    </div>

    <div class="field"> 
      <%= l.label :state %>
      <%= l.text_field :state %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, size: "40x5" %>
  </div>

  <div class="field">
      <%= form.label :pic, "Upload picture" %>
      <%= form.file_field :pic, accept: "image/png, image/gif, image/jpeg, image/jpg, image/JPG" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_questions_answers.html.erb
<div id="questions-answers">

<!-- Header -->
  <header>
    <h1>Have a question?</h1>
  </header>

<!-- Main section -->  
  <section class="session-questions-answers"> 

<!-- Display existing Q & A -->  
    <div class="div-questions-answers">
      <% @listing.questions.each do |question| %>
        <div class="field">
          <span class="label">Question: <%= question.id %></span>
          <%= question.body %>
        </div>
        <div class="field">
          <span class="label">Answer: </span>
          <%= question.answer.body if question.answer %>
        </div>
      <% end %>
    </div>

<!-- Question form: Only people other than listing owner will see 'ask question' form -->
<% if user_signed_in? and @listing.user_id != current_user.id %>
    <div class="div-questions-answers">
      <%= form_with(model: @question, local: true) do |form| %>
        <% if @question.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@question.errors.count, "error") %> prohibited this answer from being saved:</h2>

            <ul>
            <% @question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
            <%= form.label :body, "Ask a question:" %>
            <%= form.text_area :body %>
          </div>

          <div class="field hidden">
            <%= form.hidden_field :listing_id, value: @listing.id %>
          </div>

          <div class="field hidden">
            <%= form.hidden_field :user_id, value: @listing.user_id %>  
          </div>

          <div class="actions">
            <%= form.submit "Submit question"%>
          </div>
      <% end %>
    <% end %>
    </div>

<!-- Answer form: Only listing owner will see 'answer question' form -->
<% if user_signed_in? and @listing.user_id == current_user.id %>
    <div class="div-questions-answers">
      <%= form_with(model: @answer, local: true) do |form| %>
        <% if @answer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
            <% @answer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
              <%= form.label :question_id, "Enter the question number:" %>
              <%= form.text_field :question_id %>
          </div>

          <div class="field">
              <%= form.label :body, "Answer a question:" %>
              <%= form.text_area :body %>
          </div>

          <div class="actions">
          <%= form.submit "Submit answer"%>
          </div>
      <% end %>
    <% end %>
    </div>
  </section>
</div>

app/views/listings/_simple_search.html.erb
<!-- Simple search form: case insensitive, simple fuzzy search -->
<div class="search #{myclass}">
    <%= form_tag(listings_path, method: :get) do %>
        <%= label_tag(:search, "Search makeups:") %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag "Go!", :name => nil %>
    <% end %>
<div>

app/views/listings/edit.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="listing-edit">

<!-- Header -->
    <header>
        <h1>Edit Listing</h1>
    </header>

<!-- Main section: Create a new listing -->  
    <section class="session-listing">  

<!-- Created 'form' partial view to render new form & edit form -->
        <div><%= render 'form', listing: @listing %></div>
    </section>
    
<!-- Footer -->
   <%= render "shared/footer" %>
</div>

app/views/listings/index.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="listing-index">

<!-- Search: simple & advanced -->
    <div class="search-container">
        <%= render partial: "listings/simple_search", listing: @listing, locals: { myclass: "simple-search" } %>
        <%= link_to "Advanced Search", new_search_path, class: "advanced-search" %>
    </div>

<!-- Header -->
    <header>
        <h1>All Makeups</h1>
    </header>

<!-- Main section: show all the listing -->
    <section>
        <% @listings.each do |listing| %>
            <div> 
                <p><%= image_tag(listing.pic, alt: "picture of makeup listing") if listing.pic.attached? %></p>
                <%= link_to "#{listing.title}", listing_path(listing.id) %>
                <p><%= number_to_currency(listing.price) %></p>
            </div>     
        <% end %>
    </section>

<!-- Footer -->
   <%= render "shared/footer" %>
</div>

app/views/listings/new.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="listing-new">

<!-- Header -->
    <header>
        <h1>New Listing</h1>
    </header>
    
<!-- Main section: Create a new listing - partial form for new form & edit form -->  
    <section class="session-listing">  
<!-- Created -->
        <div><%= render 'form', listing: @listing %></div>
    </section>

<!-- Footer -->
   <%= render "shared/footer" %>
</div>

app/views/listings/purchase.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="listing-purchase">

<!-- Header -->
    <header>
        <h1>Purchae Confirmation</h1>
    </header>

<!-- Main section: purchase confirmation information-->
    <section>
        <div class="confirmation">
            <p>You are redirecting to a third party payment website for secure payment processing.</p>
            <p>Please press 'Continue' to confirm if you would like to continue.</p>
        </div>

        <form method="POST" action="<%= purchase_listing_path %>">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <input type="hidden" name="id" value="<%= current_user.id %>" />
            <input type="hidden" name="id" value="<%= @listing.id %>" />
            <input data-stripe="payment" type=submit value="Continue" />
        </form>

        <script src="https://js.stripe.com/v3/"></script> 

        <script>
            document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
                const stripe = Stripe("<%= @public_key %>");
                stripe.redirectToCheckout({
                    sessionId: "<%= @session_id %>"
                })
            })
        </script>
    </section>
   <%= render "shared/footer" %>
</div>


app/views/listings/show.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="listing-show">

<!-- Header -->
  <header>
    <h1><%= @listing.title %></h1>
  </header>

<!-- Main section: Show a listing -->  
  <section class="session-listing">  
    <div>
      <%= image_tag(@listing.pic, alt: "picture of makeup listing") if @listing.pic.attached? %>
    </div>

    <div class="field">
      <span class="label">Brand: </span>
      <%= @listing.brand %>
    </div>

      <div class="field">
      <span class="label">Description: </span>
      <div class="description">
        <%= @listing.description %>
      </div>
    </div>

    <div class="field">
      <span class="label">Location: </span>
      <%= @suburb %>, <%= @postcode%>, <%= @state %>
    </div>

    <div class="field">
      <span class="label">Posted by: </span>
      <%= link_to @listing.user[:username], profile_path(@listing.user_id) %>
    </div>

    <div class="field">
      <span class="label">Last updated: </span>
      <%= @listing.updated_at.strftime("%d-%m-%Y") %>
    </div>

    <div class="field">
      <span class="label">Price: </span>
      <%= number_to_currency(@listing.price) %>
    </div>

    <!-- Only people other than listing owner can see 'purchase' button -->
    <% if user_signed_in? and @listing.user_id != current_user.id %>
    <div class="field">
        <%= button_to "Purchase",  purchase_listing_path(@listing.id), method: :get %>
    </div>
    <% end %>

    <!-- Only listing owner can see 'edit' & 'delete' buttons -->
    <% if user_signed_in? and @listing.user_id == current_user.id %>
    <div class="field">
      <%= button_to "Edit", edit_listing_path(@listing), method: :get %>
    </div>

    <div class="field">
      <%= button_to "Delete", listing_path(@listing), method: :delete, data: { confirm: "Are you sure?" }%>
    </div>
    <% end %>
  </section>

<!-- 'Questions_answers' partial to render Q & A section-->
  <%= render "listings/questions_answers", listing: @listing %>

<!-- Footer -->
   <%= render "shared/footer" %>
</div>