config/routes.rb
Rails.application.routes.draw do
  # Routes - Devise (automatically created)
  devise_for :users  
  #   new_user_session GET         /users/sign_in(.:format)        devise/sessions#new
  #   user_session POST            /users/sign_in(.:format)        devise/sessions#create
  # destroy_user_session DELETE    /users/sign_out(.:format)        devise/sessions#destroy
  # new_user_password GET          /users/password/new(.:format)     devise/passwords#new
  # edit_user_password GET         /users/password/edit(.:format)   devise/passwords#edit
  #  user_password PATCH           /users/password(.:format)        devise/passwords#update
  #                PUT             /users/password(.:format)        devise/passwords#update
  #                POST            /users/password(.:format)        devise/passwords#create
  # cancel_user_registration GET   /users/cancel(.:format)         devise/registrations#cancel
  # new_user_registration GET      /users/sign_up(.:format)        devise/registrations#new
  # edit_user_registration GET     /users/edit(.:format)           devise/registrations#edit
  # user_registration PATCH        /users(.:format)                devise/registrations#update
  #                PUT             /users(.:format)                devise/registrations#update
  #                DELETE          /users(.:format)                devise/registrations#destroy
  #                POST            /users(.:format)                devise/registrations#create
  
  # Routes - Listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"

  get "/listings/:id/purchase", to: "listings#purchase", as: "purchase_listing"
  
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  delete "/listings/:id", to: "listings#destroy"
  
  # Routes - Landing Page
  get "/", to: "pages#home", as: "root"

  # Routes - Question (Only need create route, as get/form will be shown on show_listing)
  post "/listings/:id/questions", to: "questions#create", as: "questions"

  # Routes - Answer (Only need create route, as get/form will be shown on show_listing)
  post "/questions/:id/answers", to: "answers#create", as: "answers"

  # Routes - Profile (:id here is the id column in User table)
  get "/profiles/:id", to: "profiles#show", as: "profile"

  # Routes - Advanced Searches
  post "/searches", to: "searches#create", as: "searches"
  get "/searches/new", to: "searches#new", as: "new_search"
  get "/searches/:id", to: "searches#show", as: "search"

  # Routes - Payment
  get "/payments/success", to: "payments#success", as: "success_payment"
  post "/payments/webhook", to: "payments#webhook", as: "webhook_payment"
end

app/views/shared/_footer.html.erb
<footer id="footer">

<!--Footer: Social Icons -->
    <div class="social_icons">
        <ul>
            <li><a href="mailto:abm@gmail.com" target="_top" class="far fa-envelope" title="Email"><span class="label"></span></a></li>
            <li><a href="https://www.facebook.com/" target="_blank" class="fab fa-facebook-square" title="Facebook"><span class="label"></span></a></li>
            <li><a href="https://twitter.com/" target="_blank" class="fab fa-twitter-square" title="Twitter"><span class="label" ></span></a></li>
            <li><a href="https://www.instagram.com/" target="_blank" class="fab fa-instagram" title="Instagram"><span class="label" ></span></a></li>
        </ul>
    </div>

<!--Footer: Copyright -->
    <div class="copyright">
        <p>Copyright © 2019 Aussie Beauty Market. All Rights Reserved.</p>
    </div>
</footer>

app/views/shared/_nav_bar.html.erb
<!--Nav Bar-->
<nav id="nav-bar">
    <input type="checkbox" id="menu">
    <label for="menu">Menu</label>

<!--Menu inside Nav -->
    <div class="menu-content">
        <%= link_to root_path, class: "nav-link" do %><i class="fas fa-home"></i> ABM <% end %>
        <%= link_to listings_path, class: "nav-link" do %><i class="fas fa-palette"></i> All Makeups <% end %>
        <%= link_to new_listing_path, class: "nav-link" do %><i class="fas fa-paint-brush"></i> List Makeup <% end %>

        <!--Dropdown inside Menu -->
        <div class="dropdown">
            <button class="dropdown-button">
                <i class="fas fa-user-circle"></i> My ABM <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <% if user_signed_in? %>
                    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %> Log Out <i class="fas fa-door-closed"></i><% end %>
                <% else %>
                    <%= link_to new_user_session_path, class: "nav-link" do %> Log In <i class="fas fa-sign-in-alt"></i><% end %>
                    <%= link_to new_user_registration_path, class: "nav-link" do %> Sign Up <i class="fas fa-user-plus"></i><% end %>
                <% end %>
            </div>
        </div>
    </div>
</nav>