config/routes.rb
Rails.application.routes.draw do
  # Routes - Devise (automatically created)
  devise_for :users  
  #   new_user_session GET         /users/sign_in(.:format)        devise/sessions#new
  #   user_session POST            /users/sign_in(.:format)        devise/sessions#create
  # destroy_user_session DELETE    /users/sign_out(.:format)        devise/sessions#destroy
  # new_user_password GET          /users/password/new(.:format)     devise/passwords#new
  # edit_user_password GET         /users/password/edit(.:format)   devise/passwords#edit
  #  user_password PATCH           /users/password(.:format)        devise/passwords#update
  #                PUT             /users/password(.:format)        devise/passwords#update
  #                POST            /users/password(.:format)        devise/passwords#create
  # cancel_user_registration GET   /users/cancel(.:format)         devise/registrations#cancel
  # new_user_registration GET      /users/sign_up(.:format)        devise/registrations#new
  # edit_user_registration GET     /users/edit(.:format)           devise/registrations#edit
  # user_registration PATCH        /users(.:format)                devise/registrations#update
  #                PUT             /users(.:format)                devise/registrations#update
  #                DELETE          /users(.:format)                devise/registrations#destroy
  #                POST            /users(.:format)                devise/registrations#create
  
  # Routes - Listings
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"

  get "/listings/:id/purchase", to: "listings#purchase", as: "purchase_listing"
  
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  delete "/listings/:id", to: "listings#destroy"
  
  # Routes - Landing Page
  get "/", to: "pages#home", as: "root"

  # Routes - Question (Only need create route, as get/form will be shown on show_listing)
  post "/listings/:id/questions", to: "questions#create", as: "questions"

  # Routes - Answer (Only need create route, as get/form will be shown on show_listing)
  post "/questions/:id/answers", to: "answers#create", as: "answers"

  # Routes - Profile (:id here is the id column in User table)
  get "/profiles/:id", to: "profiles#show", as: "profile"

  # Routes - Advanced Searches
  post "/searches", to: "searches#create", as: "searches"
  get "/searches/new", to: "searches#new", as: "new_search"
  get "/searches/:id", to: "searches#show", as: "search"

  # Routes - Payment
  get "/payments/success", to: "payments#success", as: "success_payment"
  post "/payments/webhook", to: "payments#webhook", as: "webhook_payment"
end

app/models/search.rb
class Search < ApplicationRecord
    enum category: { face: 0, eyes: 1, lips: 2, accessories: 3 } 

    def search_listings
        listings = Listing.all
        listings = listings.where("lower(brand) LIKE ?", "%#{brand.downcase}%") if brand.present?
        listings = listings.where(category: category) if category.present?
        listings = listings.where("price >= ?", min_price) if min_price.present?
        listings = listings.where("price <= ?", max_price) if max_price.present?
        return listings
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end

    private
    
    def search_params
        params.require(:search).permit(:brand, :category, :min_price, :max_price)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="search-new">

<!-- Header -->
    <header>
        <h1>Advanced Search</h1>
    </header>

<!-- Main section-->
    <section>
        <%= form_with(model: @search, local: true) do |form| %>
            <div class="field">
                <%= form.label :brand, "Search brands"%>
                <%= form.text_field(:brand) %>
            </div>

            <div class="field">
                <%= form.label :category %>
                <%= form.select(:category, [["Face", "face"], ["Eyes", "eyes"], ["Lips", "lips"], ["Accessories", "accessories"]], :include_blank => true) %>
            </div>

            <div class="field">
                <%= form.label :min_price, "Price Range $" %>
                <%= form.text_field(:min_price) %>
                to
                <%= form.text_field(:max_price) %>
            </div>

            <div class="actions"><%= form.submit "Search"%><div>
        <% end %>
    </section>
<!-- Footer -->
   <%= render "shared/footer" %>
</div>

app/views/searches/show.html.erb
<!-- Nav bar & hero image inherited from application.html.erb -->

<div class="main" id="search-show">

<!-- Header -->
    <header>
        <h1>Advanced Search Results</h1>
    </header>

<!-- Main section-->
    <section>
        <div>
            <% if @search.search_listings.empty? %>
                <p>No Listings Found!<p>
            <% else %>
                <% @search.search_listings.each do |search| %>
                    <%= image_tag(search.pic, alt: "picture of makeup listing") if search.pic.attached? %>
                    <p><span><%= link_to "#{search.title}", listing_path(search.id) %></span></p>
                    <p>Brand: <%= search.brand %></p>
                    <p>Category: <%= search.category %></p>
                    <p>Price: <%= number_to_currency(search.price) %></p>
                <% end %>
            <% end %>
        </div>
    </section>
<!-- Footer -->
   <%= render "shared/footer" %>
</div>